build:
  stage: build
  script: |
    dotnet restore
    dotnet pack -c Release
  artifacts:
    paths:
      - bin/Release/netwatcher.*.nupkg
  tags:
    - dotnet
    - vs2017

deploy:
  stage: deploy
  when: manual
  script: |
    cd bin/Release/
    nuget push -src nuget.org netwatcher.*.nupkg
  dependencies:
    - build
  tags:
    - nuget
    - vs2017
