build:
  stage: build
  script: |
    msbuild /t:Restore
    msbuild /t:Pack /p:Configuration=Release
  artifacts:
    paths:
      - bin/Release/*
  tags:
    - vs2017

deploy:
  stage: deploy
  when: manual
  script: |
    cd bin/Release/
    nuget push -src nuget.org netwatcher.*.nupkg
  dependencies:
    - build
  tags:
    - nuget
    - vs2017
