build:
  stage: build
  script: |
    dotnet restore
    dotnet pack -c Release
  artifacts:
    paths:
      - bin/Release/netwatcher.*.nupkg
  tags:
    - jenkins
    - vs2015

deploy:
  stage: deploy
  when: manual
  script: |
    cd bin/Release/
    nuget push netwatcher.*.nupkg
  dependencies:
    - build
  tags:
    - jenkins
    - vs2015
